### ISSUE TITLE
Autocomplete species drop-down search in forms

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#251]
**Is your feature request related to a problem? Please describe.**
Currently the app brings you to the desired species just based on the first character. 

**Describe the solution you'd like**
The user wants to be brought to the species in drop-down if they start typing either the Scientific, Common name, or species Code for both Plants and Animals

- [X] MultiSelect Autocomplete Widget (from BioHub)
- [X] Single-Select Autocomplete Widget (modified)
- [ ] Get Autocomplete widgets working with x-code tables _Split out to ticket #645_ 
- [ ] Implement Autocomplete across all forms (as default behavior or custom) _Split out to ticket #645_ 
- [ ] Implement Species drop-down specifically, using the Autocomplete widget _Split out to ticket #645_ 

**Additional Context**
This ticket has been split out into #645

**Comment by ZoeSimon** [comment]
@dogcomplex Please reach out to @NickPhura for guidance on this one - request from Mike W.
