### ISSUE TITLE
All remaining layer functions prod worthy for v2

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#3028]
Some of this might just be QA but some needs tuning for sure:

- [x] All Recordset functions working as expected.
  - [ ] :zap: Clean up state updates - fix all the JSON.parse(JSON.stringify copies of state from component #3033
  - [x] Spatial Filters
    - [x] IAPP layer
    - [x] IAPP Table
    - [x] Activities Layer #3051
    - [x] Activities Table
  - [x] Activities recordset toggles #3033
    - [x] Shapes visible at max zoom
  - [x] All colours for Activities working as they should (from donut down to poly and marker
  - [x] IAPP recordset toggle
  - [x] Spinners when they should
    - [ ] :zap: On init GeoJSON fetch
    - [x] :zap: On ID get
    - [x] simple version - if its working its spinning
    - [ ] ideal version (when network and backend unpredictable): transaction based loading and cancelling of requests, probably another ticket
  - [x] Filters persist between refreshes
- [x] Whats here working perfectly. #3029
 - [x] No quirky behaviours
      - [x] Routing behaviour / navback a bit weird/clunky
        - [x] Added back button
        - [x] Fixed jumbled state a person can get in to toggling the button a few times or naving away
      - [x] The box dissapearing is weird
      - [x] The pins not highlighting 
  - [x] Loads data when it should
    - [x] Activities
    - [x] IAPP
- [x] Re-QA Whats here after holidays: #3032
    - [x] Waits until Activities & IAPP Geojson + recordsets are loaded
      - [x] Checks for Activities GeoJSON get
      - [x] Checks for IAPP GeoJSON get
      - [x] Checks for ANY recordset toggled on fetching
~~- [ ] Spinners when it should~~ I was unable to do this - the cpu is just pinned while its filtering so by the time it wants to draw spinner  its done.  Some people might see it.  It's a brief hang.
- [x] Whats here interaction with pannel toggle solid 
- [x] Labels + toggle #3044
  - [x] Activities 
  - [x] IAPP:
     Options:
    - [ ] Like for Like - have a load extent button for canvas layers * Works but sucks/clunky
    - [ ] Incorporate into donuts, and don't render until zoomed way in * TBD if works with our volume
    - [x] Auto reload based on extent - when zoomed way out only use donut * TBD if works with our volume #3043  #3044
    - [ ] Grind out the dynamic PMTile rendering code * Doesn't allow for additional filtering on mobile offline

  - [ ] :zap:  Maybe just use PMTILE layer?? Much faster, displays what isn't there although no quirky load label extent UX
- [x] Both IAPP and Activities all release ready
  - [ ] Passed my testing as prod worthy - put feedback / new issues in another ticket (easier for me to manage issues from git).
:zap: ~~Shape dicts pushed up to s3 + only one copy anywhere in state~~ is now #3031
