### ISSUE TITLE
Appv2 testing 2024-02-21

### ISSUE THREAD

**Issue by brennanwebster** [bcgov/invasivesbc#3153]
MW- NOTE:  was on prod2 not Maplibre in dev, crossing out those that are covered in current dev release:

~~- [ ] Two regional districts in layer picker~~
~~- [ ] Layer picker BCGW layers render under basemap~~
~~- [ ] Users sometime get stuck dragging recordset pane and map at the same time~~

Suggestions to consider:
- [x] Save/submit/delete button not obvious/unintuitive
- [x] Map buttons render over recordset pane when it is maximized 
MW:  They are on top so layer picker choices are available, need to review MapLibre version

- [ ] Filter on and Operator filter columns should be swapped UPDATE 08/04/2024 MW: can do

UPDATE 08/04/2024 MW:  Issue with these (particularly activity shape) is assumes you need to make no edits, otherwise the form will keep interrupting you.  Maybe a use case for whats here but activity form I think could get in the way:
- [ ] Drawing a whats here box should automatically pop out records pane 
- [ ] After drawing shape for new record form pane should automatically pop up

Should fix:
- [x] Bring back enter UTMs manually (need to port from v1)
- [x] Metabase reports not showing on reports page (known, disabled)

Duplicate / fixed with #3094
~~- [ ] Intermittent issue where filters seem to stop working, stuck on loading~~
~~- [ ] 500 on multiple iapp filters~~
