### ISSUE TITLE
Client state test harness for v2 UI

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#3170]
Expanding on our return to tests now for v2:

`npm run test` from `appv2`:

- [x] Mount and has store

- [x] #3171
- [ ] #3172
- [ ] #3173
- [ ] #3174
- [ ] Map - Layer Picker on load
  - [ ] Sane defaults on new visit
  - [ ] Remembers choices between visits
  - [ ] Loads WMS, KML, and drawn boundaries into state 

- [ ] #3175
- [ ] #3176
- [ ] Activity on select
  - [ ] Activity loads, main map marker, main blob, photos, jurisdictions, suggested treatments, etc all update.  Geo ready to update
- [ ] Activity on update
  - [ ] Local reflects remote (by taking what comes in 200), main map marker, main blob, jurisdictions, suggested treatments all update.  New geo again ready to edit.
- [ ] Activity on delete
  - [ ] Main map marker, main activity state cleared, removed from local layers without refetching.
- [ ] IAPP on select
  - [ ] Loads related stuff, main map marker updates
- [ ] Map - WhatsHere -  user draw whats here box
  - [ ] Use search shape to populate table
  - [ ] Search feature loaded for display
  - [ ] Can exit clean back to where we were
- [ ] Map - KML - user upload KML
- [ ] Tables - KML - user upload KML
- [ ] Map - Layer picker on change 
 - [ ] state, local storage, and maplibre updated (assert state and maplibre separately so we keep most of the tests portable)

Later: Batch, reports,
