### ISSUE TITLE
Create Leaflet React Map

### ISSUE THREAD

**Issue by popkinj** [bcgov/invasivesbc#352]
**Create a Leaflet map**
Creation of a map component with basic features compatible with many generic tasks. The map will be based on the [React Leaflet](https://react-leaflet.js.org/) fork of the original [Leaflet](https://leafletjs.com/) library. 

**Tasks**
- [x] Research react-leaflet
- [ ] Install react-leaflet
- [ ] Create map component
- [ ] Customize map extent
- [ ] Add layer switcher widget
- [ ] Add a number of sample basemaps
- [ ] Add an overlay (TMS or Vector)
- [ ] Add and configure editing/drawing tools

*This ticket is being supported under BCBioHub project. It is also being tracked here, as it may eventually be incorproated into the InvasivesBC project*

**Comment by micheal-w-wells** [comment]
Do you think you can get offline caching working?

**Comment by popkinj** [comment]
Yeah... may be handy here.
The main thing I'm worried about Leaflet-React is adding plugins... like how hard will it be to add the offline plugin???

Definitely worth a try though.

**Comment by micheal-w-wells** [comment]
Going to close this until someone somewhere solves the offline plugin for react-leaflet, that problem makes this out of scope for InvasivesBC for now.
