### ISSUE TITLE
Make App Mobile Friendly

### ISSUE THREAD

**Issue by LocalNewsTV** [bcgov/invasivesbc#3637]
# Describe the task
> If the task will only make sense to a dev, add a :zap: to the title.

> [!NOTE]
> Its primarily to make the app `usable` on a Cellphone. Look and feel unlikely to change for most sections.

## Value Add
- Wider range of user options
- Can check into the Web/Mobile app while on the go without need for Tablet / PC

## Acceptance Criteria

- [x] Widen the Header options to use more screen space
- [x] Map options overflow out, cannot change Map tiles, or see last button
- [x] Recordset Lists squished in `/Records`
- [x] #3513
- [x] Weird border-right-like property appears in Home Text
- [x] Top section of forms overflows out of (RJSF doesn't)
- [x] Camera button partially obstructed by footer
- [x] Tooltips overflow out of view
- [ ] ~Batch uploads rows overflow~
- [ ] ~Batch Upload Page overflows~
- [ ] ~Download Batch CSVs has major inconsistencies~
- [x] Admin Panel Email templates get Squished
- [x] Alerts overflow from Mobile
- [x] #3503 
- [x] Offline Sync Status Menu
- [x] Logo Tiny
