### ISSUE TITLE
Map component cleanup

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#3689]
Meghna to work with Mike to migrate maplibre code to react components, will work with Rob before we make big sweeping changes.  This will simplify the map quite a bit and make it closer to the new maps getting built on other apps accross DDS and be a good onboarding/training exercise for Meghna to have head wrapped around all map code.

Note that layers not yet migrated to a component can still work with old maplibre lib code fired off in a hook.

- [x] Prove out component for public map layer / pmtile 
- [x] Prove out for InvasivesBC/IAPP express vector endpoints (including auth)
- [x] #3690
- [x] #3728 
- [ ] Map tools to migrate:
  - [ ] Toggles
  - [ ] Track me
  - [ ] Whats here
  - [ ] Draw tools.
- [ ] Cached layers
