### ISSUE TITLE
Shasko's ticket to-do

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#394]
**Current Sprint**
- [x] Ticket #320 - ??
- [x] Ticket #157 - shasko updated

**These are just questions so hoping they can be ASAP**
- [x] Ticket #401 - shasko updated
- [x] Ticket #402 - shasko updated

**Upcoming Sprints**
- [x] Form ticket creation/discussion with Shreyas. _put at top of backlog to action in Jan 21st Sprint_
- [ ] Ticket #121 - shasko updated
- [x] Ticket #386
- [ ] Ticket #323
- [x] Ticket #318

...to be continued

**Comment by micheal-w-wells** [comment]
Question about code tables for @mikeshasko  and @rstens:  Title and description (and i think one more column) of the code table header are all the same.  Are there plans to do anything about that?  This can be a ticket to track work if so if not answer here for @klefler  and we can close.

**Comment by micheal-w-wells** [comment]
Do we want to roll with "primary_user_name_1" or "observer_1" ? The Form spec and API and DB are mismatched.

@mikeshasko  @klefler
