### ISSUE TITLE
Pre-user testing issues list

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/invasivesbc#540]
Crystal's gonna say it needs to happen, or will be annoyed with symptom of it not being done:
- _Broken into new ticket_ can we tell user there are too many in the area to fetch? -wk
- [x] add index to pouch query - mw 
- [x] batch insert into pouch - wk
- [x] point of interest bug - clicking POI on map - wk

_Broken into new ticket_ Would be nice:
- leaflet cluster markers
- finish POI photos
- clicking activities on map creates blank bottom menu - either fill that in with edit form / activity data, or disable it
- side-scroll bar on IAPP table styling (too dark)
- success/error message presentation - the stack is a bit clunky

_Broken into new ticket_ Maybe temporarily passable bugs
- Plan My Trip page controls sometimes unresponsive after Wipe Local Data pressed.  Need to switch tabs and wait
- (seems to appear on multiple pages, semi-randomly)  Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in ActivityListItem (at ReferenceActivitiesList.tsx:128)
