### ISSUE TITLE
Offline Overlays

### ISSUE THREAD

**Issue by popkinj** [bcgov/invasivesbc#604]
# Description
The [Offline Layer](https://github.com/allartk/leaflet.offline) plugin only stores one layer out of the box. There is a default control that adds buttons to the map. One button to offline the basemap, and another to clear stored tiles. This is the current setup. 

When the user clicks the offline button there is a long delay while it is calculating the required tiles, requesting and storing them.. To the user, it appears the window is frozen and unresponsive. If zoomed too far out the delay is fairly long.

I've been digging into the [API documentation](https://github.com/allartk/leaflet.offline/blob/master/docs/api.md). I think we need to address the following enhancements:
- [x] Roll a custom button that will cache all layers, not just the basemap.
- [x] Draw a boundary for cached area
- _Report number of tiles about to be cached (decided not to do because it means nothing to user [i.e. through user testing])_
- [ ] Button to be disabled at higher scales (handled in ticket #676)
- [x] Indicator that caching is in progress
- [ ] Feedback to user when caching is complete (handled in ticket #673)
- [ ] Push caching to a webworker (handled in ticket #675)

**Comment by popkinj** [comment]
Hey @ZoeSimon 
I think this is the one we need to bust apart into smaller tickets. Working on it now and will give you a ring.

**Comment by popkinj** [comment]
![Screenshot from 2021-03-31 11-57-52](https://user-images.githubusercontent.com/479074/113196641-9618a500-9218-11eb-8133-33523ee247ed.png)
Here's the list of potential sub-tickets @ZoeSimon 

Edit - Of course now that it's posted, I notice all the terrible spelling mistakes.
