### ISSUE TITLE
Transect/Dispersal Form Updates

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/invasivesbc#610]
**From March 4th Transect meeting**
**Transect form changes [Vegetation & Biocontrol]**

**Quick fixes:**
- [x] LABEL CHANGE: Special forms can and should be changed to a different name ... "Enhanced Collections"... _We're going to be changing this again once we figure out the page display/workflow/linking - ZSimon March 8th_
- [x] LABEL CHANGE: Offset name needs to be changed to "plot distance"
- [x] LABEL CHANGE: UTM Easting & UTM northing added to box title
- [x] LABEL CHANGE: "Count Type" Change to "Cover Method" and it will say "Please specify the method of capturing cover"
- [x] LABEL CHANGE: Percent cover, Plant Count and Percent Cover Class (changed from Percent Cover, Number of Plants, & Daubenmire Classification)
- [x] LABEL CHANGE: Vegetation transect points should be renamed to **vegetation transect plots** (and help text added that says "how many plots along this transect"
- [x] LABEL CHANGE: Vegetation transect species should be renamed to "Species within Plot
- [x] NEW FIELD TO GLOBAL tier:  The field should be labelled "plot location", and drop-down options should be Left, right, or split middle. Help text can be "name your plot location in relation to transect."
- [x] MOVE: Move the Sampler and recorder name fields FROM the point tier to the transect line tier

**In progress:**
- [x] Phenology goes into biological treatment and efficacy monitoring form and be deleted from the biocontrol transect form
- [x] Sum 6 vegetation variables (Native forbs to Litter ) to "Vegetation Total Percentage"
- [x] Change the help text on those 6 veg variables to say "Percentage of ..." rather than "Number of ..."

**ITEMS MOVED TO 599** 

> - When "Percent Cover" is selected under "Cover Method (fmr Count Type), the "Species within plot (fmr Vegetation Transect Points)" can’t add to more than 100% for that plot. Net sum cannot exceed 100% for "Percent Covered" (this is similar behavior to what we have in place for jurisdiction.
> - ADDITIONAL FIELD: Beside "Cover Method (fmr Count Type)" drop-down, add new field with drop-downs for Basal Cover & Foliar Cover and label this new field as "Cover Type"
> - LABEL CHANGE: name the buttons to be "add transect" "add plot" instead of "add item"
> - Each transect is a different colour for ease of viewing? if possible? (In relation to above point "auto-generate number in the "Sample Point I.D." when additional items are added for both Transect and Plot.")
> - FIELD BEHAVIOUR CHANGE: auto-generate number in the "Sample Point I.D." when additional items are added for both Transect and Plot (i.e. 1, 2, 3, 4, ...).
> - Phenology ...  they will be held under an accordian titled "additional details" (that only shows up if selected by user)
> Additional information:
> - Testing needed to ensure that user can't proceed when invalid fields entered (in lieu of warnings displayed to user when invalid fields entered)
> - Additional Ticket will be created to address workflow, record linking etc. after call with Crystal on morning of March 8th -ZSimon

Related requirements
- [ ] Biocontrol collection form needs to be built, details & spreadsheet in ticket #608
- [x] Polygon or Circle around transect lines? This was flagged as needing a decision point at the beginning of the meeting. **This can stay as status quo. Upon further training and understanding from Dustin / Susan and other transect users, we can assess if/how the transect basic geometry should be defined**
- [ ] Basic information of polygon location, UTMs of specific transect collected down in form. Need Basic information to also have UTMs available on transect forms to supplement general location, people think in UTMs not lat/long (ticket for UTM in all other forms #607)
- [ ] help text change for phenology under the bio treatment & bio efficacy monitoring (the monitoring form of the treatment), once the forms are more finalized after meeting on Tuesday, @mikeshasko to send spreadsheet to Susan to obtain help-text.

@mikeshasko to clarify this image
![image](https://user-images.githubusercontent.com/62561887/110039066-87ac9b80-7cf5-11eb-9b50-18afdf5c1083.png)

**Comment by ZoeSimon** [comment]
@mikeshasko & @dogcomplex to work on Monday from 10-1.
These changes need to completed in advance of Tuesdays User Testing with the transect stakeholders.

**Comment by ZoeSimon** [comment]
ORIGINAL MEETING NOTES: 

**From March 4th Transect meeting**
**Transect form changes [Vegetation & Biocontrol]**
- [x] Polygon or Circle around transect lines? This was flagged as needing a decision point at the beginning of the meeting. **This can stay as status quo. Upon further training and understanding from Dustin / Susan and other transect users, we can assess if/how the transect basic geometry should be defined**
   - @micheal-w-wells do you have a better solution for having the lines stand alone (and be buffered) to actually have them displayed on the map instead of the polygon housing the lines, and having the buffered line populating the parent data fields?
- [ ] Special forms can and should be changed to a different name
- [ ] Basic information of polygon location, UTMs of specific transect collected down in form. Need Basic information to also have UTMs available on transect forms to supplement general location, people think in UTMs not lat/long (ticket for UTM in all other forms #607)
- [ ] Need to develop the transect lines first, then go back and make your plots along the transect
- [ ] each transect is a different color for ease of viewing? if possible?
- [ ] Percent cover, Plant Count and Percent Cover Class (changed from Percent Cover, Number of Plants, & Daubenmire Classification)
- [ ] Can’t be more than 100% for the one plot. Net sum cannot exceed 100%
- [ ] Add additional drop-downs for basal and foliar
- [ ] UTM Easting & UTM northing added to box title
- [ ] name the buttons to be "add transect" "add plot"
- [ ] warnings displayed to user when invalid fields entered
- [ ] Vegetation transect points should be renamed to vegetation transect plots (and help text added that says "how many plot along this transect"
- [ ] Vegetation transect species should be "Species within Plot"
- [ ] number the transects and plot number (transect 1, Transect 2 etc.)
- [ ] Phenology goes into biological treatment and monitoring with a drop down, and not mandatory
- [ ] Change the help text for phenology
- [ ] Biocontrol efficacy transects - move the lumped transect data fields over. (see picture below)
- [ ] Offset name needs to be changed to "plot distance"
- [ ] Left, right, split middle plot location in relation to transect
- [ ] Biocontrol collection form ticket #608

@mikeshasko to clarify this image
![image](https://user-images.githubusercontent.com/62561887/110039066-87ac9b80-7cf5-11eb-9b50-18afdf5c1083.png)

**Comment by ZoeSimon** [comment]
Hey @micheal-w-wells, Crystal wanted to know your take on this: 

- [x] Polygon or Circle around transect lines? This was flagged as needing a decision point at the beginning of the meeting. **This can stay as status quo. Upon further training and understanding from Dustin / Susan and other transect users, we can assess if/how the transect basic geometry should be defined** - MShasko
   
From Cystal: @micheal-w-wells do you have a better solution for having the lines stand alone (and be buffered) to actually have them displayed on the map instead of the polygon housing the lines, and having the buffered line populating the parent data fields?


Buffering the individual transect lines would look / act problematically especially if we opt to display the individual points on the line.
A simple nominal point (1m poly)  collected (automatically) at the site of the first transect line could define the "base" polygon.
