### ISSUE TITLE
Timebox Shreyas March 15-19

### ISSUE THREAD

**Issue by ghost** [bcgov/invasivesbc#638]
These are prioritized elements to fix / address with Shreya/Warren/Shasko

Formally tickets #599 #610 #533 #467

### Front-end GUI fixes:
- [ ] as per SME discussions, please remove tank volume (and its associated elements) from the herbicide sub form (#467 left over)

### Behavior fixes on actions/selections ( Validation rules, Required Fields & Typos)
- [x] Should be able to enter a second observer (chem treat)
- [x] Should be a maximum temp for herbicide treatment, didn’t flag an error when 30 degrees selected.  (chem treat)
- [x] Humidity should not be a required field (verify on chem treatment form)
- [x] Soil texture should not be a required field  (chem treat)
- [x] Secondary applicator should not be a required field  (chem treat)
- [x] Negative observation box needs to be added for each species now that we enables multiple species
- [x] Should not be able to put a negative percent in for Jurisdiction
- [x] REMOVE "Biocontrol field": 
![image](https://user-images.githubusercontent.com/62561887/109701538-fd730480-7b47-11eb-8d09-01b2a174d369.png)
- [x] When you select a negative observation as a "yes", you still have to select the density, distribution and lifestage. (i.e these fields should not be mandatory for negative observations)

### Form design fixes:
- [ ] Basic information of polygon location, UTMs of specific transect collected down in form. Need Basic information to also have UTMs available on transect forms to supplement general location, people think in UTMs not lat/long (ticket for UTM in all other forms #607)
- [ ] Biocontrol collection form needs to be built, details & spreadsheet in ticket #608
- [ ] help text change for phenology under the bio treatment & bio efficacy monitoring (the monitoring form of the treatment), once the forms are more finalized after meeting on Tuesday, @mikeshasko to send spreadsheet to Susan to obtain help-text.

### Workflow complex
- [ ] Biocontrol Collection form (net new) # 608
